### ISSUE TITLE
kazv build broke

### ISSUE THREAD

**Issue by KiaraGrouwstra** [XYenon/nur-packages#14]
i'm sure you knew this given the CI failures.
i'm just hoping to get a thread to subscribe to to learn when i can reenable this. :sweat_smile:

**Comment by XYenon** [comment]
It looks like it caused by the catch2 >= 3.5.0, you can try to downgrade nixpkgs to before [this commit](https://github.com/NixOS/nixpkgs/pull/273712). And it should be finally fixed by libkazv.

**Comment by tusooa** [comment]
https://lily-is.land/kazv/libkazv/-/merge_requests/63 should fix this.
